### PR TITLE
Installer is broken when adjusting driver for low latency

### PR DESCRIPTION
**Pull request by vizh**

### CODE REVIEW

**Comment by Wouter1** [comment]
Thanks vizh for pointing this out! It was fixed, but slightly different, using
```
	cd "$pathname"
```

**Comment by vizh** [comment]
Thanks!

**Comment by vizh** [comment]
cd "$pathname" not working because dirname $0 is "." and cd "$pathname" has no effect.

**Comment by Wouter1** [comment]
You have a problem with the script? What does the error message say?
Or do you want an explanation?
How are you starting the script? Double clicking it?

**Comment by Wouter1** [comment]
Checked, it seems you are trying to run the installer manually from the command line. Indeed that was failing. I merged your suggestion. Thanks!

**Pull request closed without merging**
